tests:
  - - - [[1,3],[2,6],[8,10],[15,18]]
    - [[1,6],[8,10],[15,18]]
  - - - [[1,4],[4,5]]
    - [[1,5]]
  - - - [[1,4],[2,3]]
    - [[1,4]]
  - - - [[1,4],[0,2],[3,5]]
    - [[0,5]]
  - - - [[1,3],[7,9],[4,6],[10,13]]
    - [[1,3],[4,6],[7,9],[10,13]]
  - - - [[6,8],[1,9],[2,4],[4,7]]
    - [[1,9]]
  - - - [[3,5],[12,15],[2,4],[10,11]]
    - [[2,5],[10,11],[12,15]]
  - - - [[1,10],[2,3],[4,5],[6,7],[8,9]]
    - [[1,10]]
  - - - [[2,3],[5,5],[2,2],[3,4],[3,4]]
    - [[2,4],[5,5]]
  - - - [[1,4],[0,0],[3,3],[2,2]]
    - [[0,0],[1,4]]
