tests:
  - - [[4, 2, 3], 1]
    - 9
  - - [[-1, -2, -3], 2]
    - 4
  - - [[1, 2, 3], 2]
    - 6
  - - [[-1, 3, -2, 4], 2]
    - 10
  - - [[0, 9, -3, 8], 1]
    - 20
  - - [[-5, -6, -7], 1]
    - -4
  - - [[10, -1, -1, 10], 2]
    - 22
  - - [[-4, -2, 1, 3], 3]
    - 10
  - - [[1, 1, 1, 1], 4]
    - 4
  - - [[-1, 2, -3, 4], 4]
    - 10
