# Test cases for the longest subarray summing to zero problem

tests:
  - - - [6, -5, 9, -10, 3]
    - 4
  - - - [-7, 4, -7, 5]
    - 0
  - - - [0, 3, -1, -1, -4, -6, -1]
    - 1
  - - - [-9, -10, 0, 0, 4]
    - 2
  - - - [-5, -7, 4, -8, -10]
    - 0
  - - - [-6, -6, -9, 7, 6, 8]
    - 6
  - - - [2, 0, -9, -6, 8, -1]
    - 1
  - - - [-2, 1, -4, 4, 3, 2, 3]
    - 2
  - - - [0, 4, -6, -1]
    - 1
  - - - [-4, 9, 10, 0, -8]
    - 1
  - - - [-1, 2, 3, -4, 9]
    - 4
  - - - [10, 1, -1, 3, 8, 5, -9, 9]
    - 2
  - - - [-7, -4, 4, 6, -7]
    - 2
  - - - [-5, 10, 5, -7, -5]
    - 0
  - - - [9, -6, 5, 6, -2, -9]
    - 4
  - - - [3, -8, 1, 2, -10, 2]
    - 0
  - - - [4, -10, -6, 10, 9, 9, 8, 2]
    - 0
  - - - [3, -2, -5, 7]
    - 3
  - - - [6, 9, -4, 7, -7]
    - 2
  - - - [0, 0, -4, 1]
    - 2
