# Test cases for the Minimum Window Substring problem

tests:
  - - [ADOBECODEBANC, ABC]
    - BANC
  - - [a, a]
    - a
  - - [a, aa]
    - ""
  - - [bdab, ab]
    - ab
  - - [thisisateststring, tist]
    - tstri
  - - [geeksforgeeks, ork]
    - ksfor
  - - [window, wind]
    - wind
  - - [timetopractice, toc]
    - toprac
  - - [zoomlazapzo, oza]
    - apzo
